language: node_js
node_js:
- "node"
jobs:
  include:
  - stage: Lint
    script: npm run lint
  - stage: Flow
    script: npm run flow
  - stage: Test
    script: npm test
  - stage: Build
    script: npm run build
after_success:
- npm run coveralls
