// @flow

export const FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY || '';

export const FIREBASE_AUTH_DOMAIN = process.env.REACT_APP_FIREBASE_AUTH_DOMAIN || '';

export const FIREBASE_DATABASE_URL = process.env.REACT_APP_FIREBASE_DATABASE_URL || '';

export const FIREBASE_MESSAGING_SENDER_ID = (
  process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID || ''
);

export const FIREBASE_PROJECT_ID = process.env.REACT_APP_FIREBASE_PROJECT_ID || '';

export const FIREBASE_STORAGE_BUCKET = process.env.REACT_APP_FIREBASE_STORAGE_BUCKET || '';

export const REDIRECT_QUERY_PARAMETER = process.env.REACT_APP_REDIRECT_QUERY_PARAMETER || '';

export const REDIRECT_REFRESH_TOKEN_PLACEHOLDER: string = (
  process.env.REACT_APP_REDIRECT_REFRESH_TOKEN_PLACEHOLDER || ''
);
