export const NAVIGATE = 'NAVIGATE';

export const FIREBASE_APP_CREATED = 'FIREBASE_APP_CREATED';
export const FIREBASE_APP_UPDATED = 'FIREBASE_APP_UPDATED';
export const FIREBASE_APP_DELETED = 'FIREBASE_APP_DELETED';

export const FIREBASE_APP_SELECTED = 'FIREBASE_APP_SELECTED';
